MNT Fix scss lint warnings
silverstripe-australia/advancedworkflow pull request #538
Opened 2024-06-10 23:10 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/.github/issues/228

2024-06-10 23:12 UTC, GuySartorelli commented on client/src/styles/WorkflowField.scss
>            background: linear-gradient($white, $grey-lightish);
linear-gradient is supported for all browsers we care about. Everything else here was old fallbacks

2024-06-11 23:46 UTC, emteknetnz approved these changes

2024-06-11 23:46 UTC, emteknetnz requested changes
Merge conflict

2024-06-12 03:43 UTC, emteknetnz approved these changes

2024-06-12 03:43 UTC, merged